apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: iojasdjangocicd 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: iojasdjangocicd 
    spec:
      containers:
        - name: iojasdjangocicd 
          image: armcontainertestsifter.azurecr.io/iojasdjangocicd
          ports:
          - containerPort: 8000