apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: djangocicd2 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: djangocicd2 
    spec:
      containers:
        - name: djangocicd2 
          image: djangocicd2.azurecr.io/djangocicd2
          ports:
          - containerPort: 8000